spring:
  jpa:
    #하이버네이트 쿼리 로그 뷰 설정
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#    hibernate:
#      ddl-auto: update

    # 테이블 생성 후 data.sql 실행
    defer-datasource-initialization: true

  datasource:
    url: jdbc:h2:mem:testdb
    username: sa

  h2:
    console:
      enabled: true