--CREATE TABLE member (id bigint generated by default as identity, name varchar(255) not null, primary key (id));

INSERT INTO member (id, name) VALUES (1, 'name 1');
INSERT INTO member (id, name) VALUES (2, 'name 2');
INSERT INTO member (id, name) VALUES (3, 'name 3');
